config/routes.rb
Rails.application.routes.draw do

   root 'static#home'

   match '/auth/:provider/callback', to: 'session#create', via: [:get, :post]
   match 'auth/failure', to: redirect('/'), via: [:get, :post]
   match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

   get 'search' => 'searchables#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.locale = auth.locale
      user.oauth_token = auth.credentials.oauth_token
      user.oauth_expires_at = Time.at(auth.credentials)
      user.save!
    end
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def current_user 
    @current_user ||=User.find(session[:user_id]) if session[:user_id]

  end

  helper_method :current_user
end

app/controllers/searchables_controller.rb
class SearchablesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user_id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
  protected

  #def auth_hash
  #  request.env['omniauth.auth']
  #end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  
  def home 
  end

  def user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searchables_helper.rb
module SearchablesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Searchme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<div id="user-widget">
  <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>

  <%= link_to "Sign out", signout_path, id: "sign_out" %>
</div>
</body>
</html>

app/views/searchables/index.html.erb
<h1>Searchables#index</h1>

<div id="calendar"></div>